# Generated by Django 4.2.6 on 2023-10-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
