# Generated by Django 4.2.6 on 2023-10-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_alter_depositoptions_intr_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate2',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='depositoptions',
            name='save_trm',
            field=models.IntegerField(default=-1.0),
        ),
    ]
