# Generated by Django 4.2.6 on 2023-10-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0007_alter_depositoptions_intr_rate2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate',
            field=models.FloatField(blank=True, default=-1.0, null=True),
        ),
    ]
