# Generated by Django 4.2.2 on 2023-09-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='desciption',
            new_name='description',
        ),
    ]
